version: '3.4'

services:
  dev:
    image: node:12-alpine
    container_name: store_api_dev
    command:  npm run dev
    working_dir: /api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached

    depends_on:
      - db

  db:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=exempla
    container_name: bq-api-node_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data


volumes:
  database:

